#!/bin/sh

# -----------------------------
# Uncomment to skip operator confirmation prior to rebooting:
#DONT_ASK_TO_CONFIRM_WRITE="1"

cecho()
{
  RED='\033[0;31m'
  GRN='\033[0;32m'
  YEL='\033[0;33m'
  BYEL='\033[1;33m'
  NC='\033[0m'
  REV='\033[0;7m'

  case $1 in
    FAIL)
      COLOR=$RED ;;
    PASS)
      COLOR=$GRN ;;
    WARN)
      COLOR=$BYEL ;;
    NOTE)
      COLOR=$YEL ;;
    YN)
      COLOR=$REV ;;
    *)
      COLOR=$NC ;;
  esac

  printf "${COLOR}${2}${NC}"
}

clear_line()
{
  CLRLINE='\033[K'

  printf "\r${CLRLINE}"
}

prompt_yn()
{
  prompt="${1} (y,n)?"
  len=${#prompt}

  while [ 1 ]; do
    cecho "YN" "$prompt"
    read -r resp
    clear_line

    if [ "${resp}" = "n" -o "${resp}" = "N" ]  ; then
      result=1
      break
    elif [ "${resp}" = "y" -o "${resp}" = "Y" ]  ; then
      result=0
      break
    else
      cecho "YEL" "-- Please input y(Y) or n(N)! --\n"
    fi
  done

  return $result
}

sh /root/flash_vl805
if [ $? -ne 0 ]; then
  exit 1
fi

sh /root/flash_eth7800
if [ $? -ne 0 ]; then
  echo "Can't find eth7800 chip.  A reboot is required after initial vl805 programming."
  prompt_yn "OK to reboot?"
  if [ $? -ne 0 ]; then
    exit 1
  else
    reboot
    exit 0
  fi
elif [ $? -ne 0 ]; then
  exit 1
fi
