#!/bin/sh

# -----------------------------
# Uncomment to skip operator confirmation prior to rebooting:
#DONT_ASK_TO_CONFIRM_WRITE="1"

cecho()
{
  RED='\033[0;31m'
  GRN='\033[0;32m'
  YEL='\033[0;33m'
  BYEL='\033[1;33m'
  NC='\033[0m'
  REV='\033[0;7m'

  case $1 in
    FAIL)
      COLOR=$RED ;;
    PASS)
      COLOR=$GRN ;;
    WARN)
      COLOR=$BYEL ;;
    NOTE)
      COLOR=$YEL ;;
    YN)
      COLOR=$REV ;;
    *)
      COLOR=$NC ;;
  esac

  printf "${COLOR}${2}${NC}"
}

clear_line()
{
  CLRLINE='\033[K'

  printf "\r${CLRLINE}"
}

prompt_yn()
{
  prompt="${1} (y,n)?"
  len=${#prompt}

  while [ 1 ]; do
    cecho "YN" "$prompt"
    read -r resp
    clear_line

    if [ "${resp}" = "n" -o "${resp}" = "N" ]  ; then
      result=1
      break
    elif [ "${resp}" = "y" -o "${resp}" = "Y" ]  ; then
      result=0
      break
    else
      cecho "YEL" "-- Please input y(Y) or n(N)! --\n"
    fi
  done

  return $result
}

# Suppress all but panic kernel messages from appearing on the console
dmesg -n 1

echo ""
cecho "NOTE" "------------------------\n"
cecho "NOTE" " MTP CM4 F1 Programming \n"
cecho "NOTE" "------------------------\n"
echo ""

sh /root/flash_vl805
retcode=$?
if [ $retcode -ne 0 ]; then
  echo ""
  cecho "FAIL" "F1 VL805 Programming failed with code $retcode\n"
  exit 1
fi

sh /root/flash_eth7800
retcode=$?
if [ $retcode -eq 10 ]; then
  cecho "WARN" "A reboot is required after initial vl805 programming to find eth7800.\n"
  echo ""
  prompt_yn "OK to reboot?"
  if [ $? -ne 0 ]; then
    echo ""
    cecho "FAIL" "F1 eth7800 Programming failed with code $retcode\n"
    exit 1
  else
    reboot
    exit 0
  fi
elif [ $retcode -ne 0 ]; then
  echo ""
  cecho "FAIL" "F1 eth7800 Programming failed with code $retcode\n"
  exit 1
fi

while [ 1 ]; do
  sh /root/test_usb2_3xflash
  retcode=$?
  if [ $retcode -eq 0 ]; then
    break
  fi

  prompt_yn "Verify 3x USB2 High-Speed flash drives are installed, retry"
  if [ $? -ne 0 ]; then
    echo ""
    cecho "FAIL" "F1 USB Port testing failed with code $retcode\n"
    exit 1
  fi
done

echo ""
cecho "PASS" "F1 testing is complete - PASSED\n"
