#!/bin/sh

FLASH_FILE="/root/see_7800.bin"

result=$(lsusb | grep "0424:7800")
if [ $? != 0 ]; then
    echo "*** FAIL: LAN7800 Gb Ethernet not found"
    exit 2
fi

result=$(ethtool -E eth1 magic 0x78A5 offset 0 length 254 < $FLASH_FILE)

if [ $? != 0 ]; then
    echo "*** FAIL: Flashing of LAN7800 EEPROM Failed"
    exit 3
fi

result=$(i2cdump -y -r 0xfa-0xff 10 0x50 b | tail -n 1)

if [ $? != 0 ]; then
    echo "*** FAIL: Reading of EEPROM MAC address Failed"
    exit 4
fi
mac=$(echo $result | cut -b 4-21)
echo "Result: $result"
echo "MAC: $mac"
result=$(echo $mac | xxd -p -r | ethtool -E eth1 magic 0x78A5 offset 1 length 6)


if [ $? != 0 ]; then
    echo "*** FAIL: Program of LAN7800 MAC address Failed"
    exit 5
fi

echo "PASS: LAN7800 Programming (MAC: $mac)"

exit 0
